# Generated by Django 4.0.5 on 2023-01-13 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatb', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatbotInteraction',
        ),
    ]
